### ISSUE TITLE
Apply New UI to Gallery Module

### ISSUE THREAD

**Issue by cosmomathieu** [pagestudiocms/cms#55]
**Completed**
- [x] Created a new admin UI
- [x] Reworked the gallery module to support new UI

**Need to be completed**
- [x] Add album cover to albums
- [x] Add ability to sort by drag and drop
- [x] Add Fancybox for viewing images as a gallery

**Comment by cosmointeractive** [comment]
Done
- [x] Created a new admin UI
- [x] Reworked the gallery module to support new UI

 Need to be done
- [ ] Add album cover to albums
