### ISSUE TITLE
.HTAccess Problem

### ISSUE THREAD

**Issue by mdestafadilah** [pagestudiocms/cms#64]
I have problem with my .htaacess, my subfolder

ROOT
-----WEB
-----------application
-----------system
-----------themes
index.php
.htaccess

but my themes folder can't get right folder, the folder under "WEB" folder...

this my htaccess:
```
## Set up mod_rewrite
<IfModule mod_rewrite.c>
Options +MultiViews +FollowSymLinks
DirectoryIndex index.php index.html

# Enable Rewrite Engine
# ------------------------------
RewriteEngine On

# UPDATE THIS TO POINT TO where you installed this FROM YOUR DOC ROOT.
# If this is in the DOC ROOT, leave it as it is
# ---------------------
# RewriteBase /WEB/

# In case your hosting service doesn't add or remove 'www.' for you, you can
# do it here by uncommenting and updating the 'Rewrite*'s below.
#
# Add or remove 'www.'  Whichever you prefer.  
# This one removes the 'www.' which seems to be the favorable choice these days. 
# ------------------------------
#RewriteCond %{HTTP_HOST} ^www.<sitename>.com
#RewriteRule (.*) http://<sitename>.com/$1 [R=301,L]

# Redirect index.php Requests
# ------------------------------
RewriteCond %{THE_REQUEST} ^GET.*index\.php [NC]
RewriteCond %{THE_REQUEST} !/system/.*
RewriteRule (.*?)index\.php/*(.*) $1$2 [R=301,L]

# Standard ExpressionEngine Rewrite
# ------------------------------
RewriteRule modules/(.+)/controllers/(.+)\.php$ /index.php?/$1/$2 [L,R=301]
RewriteRule controllers/(.+)\.php$ /index.php?/$1 [L,R=301]

RewriteCond $1 !\.(css|js|gif|jpe?g|png) [NC]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]
</IfModule> 
```

Thanks...

**Comment by cosmomathieu** [comment]
What is your website path from the browser? Is it something like http://website.com or http://website.com/folder/?

You may not need to define `RewriteBase /WEB/` try leaving it as `RewriteBase /`

**Comment by mdestafadilah** [comment]
my root path, yes, http://website.com and same result ... ithink the problem is in apache and .htaccess ... with your htaccess have some problem too... 

try out my application and system same position ... with root path.... tomorow i will try..

have anice weekend...

**Comment by cosmomathieu** [comment]
What is your server environment? Are you using WAMP, XAMP? Ubuntu (if so which version)? I want to replicate your environment so I can test.

**Comment by mdestafadilah** [comment]
It's working if my application,system,assets, themes, etc. in root folder.

root_folder
------Web
------CI-CMS
----------------PageStudioCMS
application
system
assets
themes
index.php
.htaccess

I'm using CentOS, with LAMP, i don't know why it's so different from  my application others, with modules system, thats my htaccess before is working..

**Comment by cosmomathieu** [comment]
I'll have to test that on CentOS. What version of Apache are you using?

**Comment by mdestafadilah** [comment]
![apache](https://cloud.githubusercontent.com/assets/5575882/26706593/ca743746-4768-11e7-8d01-083444e6de47.png)
![github](https://cloud.githubusercontent.com/assets/5575882/26706594/ca766c00-4768-11e7-8a4b-a2482fad6f8b.png)

**Comment by cosmomathieu** [comment]
Sorry, I've been working on other features. I'll take a look at these issues within the next two weeks. Hopefully I can fix them then.

**Comment by mdestafadilah** [comment]
Yes, it's working now... i must installed in fresh server... i don't know why... but it's resolved. Thanks for your attention brothers.
