### ISSUE TITLE
Add Image Path 

### ISSUE THREAD

**Issue by mdestafadilah** [pagestudiocms/cms#72]
Just add image from content entries, but not get spesific 'path' with file manager, just output url

http://localhost/application/third_party/file_manager/dialog.php?type=1&popup=1&field_id=image_placeholder

why ADMIN_PATH not redirect selft to:

http://localhost/lmpattra/application/third_party/file_manager/dialog.php?type=1&popup=1&field_id=image_placeholder

i put pagestudiocms inside root folder, i create name lmpattra folder.

Thanks, i'm also checking what's going on.

**Comment by cosmomathieu** [comment]
I don't understand your question.

**Comment by mdestafadilah** [comment]
sorry my mistake, i think file_manager (plugin) not read root url .
