### ISSUE TITLE
Did you add Google Analytics in Module

### ISSUE THREAD

**Issue by mdestafadilah** [pagestudiocms/cms#73]
Hi,
I can't find, any analytics, or i'm missing here?

Thanks

**Comment by cosmomathieu** [comment]
Yes. GA is available. Go to System > General Settings > Analytics

**Comment by mdestafadilah** [comment]
I mean, in docs (documentation) .. with google apps now ... it's different .. have you try it?

**Comment by cosmomathieu** [comment]
What are you trying to do? What's missing? Mine still works on version 1.2.0. I'll test 1.3.x, but nothing changed from 1.2.x - 1.3.x with regards to Analytics.

**Comment by mdestafadilah** [comment]
Yes, i'm new in GA ... so i figure out in NET what is GA id, and others... but still not work, next monday i will give you scrennshoot. setting i do.

**Comment by mdestafadilah** [comment]
Yes, here error i get ... any ide why? or i'm missing with GA Librarry default?
![erro-ga](https://user-images.githubusercontent.com/5575882/32588140-463a861a-c53f-11e7-832f-7a4ffd07fd0b.png)

**Comment by cosmomathieu** [comment]
It looks like you might have the wrong `Profile ID` (now called `View ID`). You need both your `View ID` and your `Google Analytics Tracking Code`. See the following two screenshots on how to locate your `Profile/View ID`.

1. Login to your GA account
2. Go to settings 
3. Click on **Account** > **Property** > **View** > **View Settings**

![screenshot-1](https://user-images.githubusercontent.com/7852494/35092055-39099860-fc0c-11e7-9c77-a62413240d0d.jpg)

![screenshot-2](https://user-images.githubusercontent.com/7852494/35091718-4e82983c-fc0b-11e7-9b12-b6b795dc21e0.jpg)

In PageStudio CMS here is how you enter the information. **GA Profile ID** is the **View ID**.
![screenshot-3](https://user-images.githubusercontent.com/7852494/35092276-e16c961a-fc0c-11e7-8dfb-e62be75f07a9.jpg)

**Comment by mdestafadilah** [comment]
Wait brothers, it's not clear.. are you change library GA in PageStudioCMS it' self? i'm trying testing in canvasCMS .. 

**500 ... Internal Server Error**

[http://127.0.0.1/cms/dashboard/get-ga-data](http://127.0.0.1/cms/dashboard/get-ga-data)

Thanks.

**Comment by cosmomathieu** [comment]
No. I didn't change anything in the library. Nothing in the code needs to change from what I can tell. See the screen below: 

Log into PageStudioCMS and navigate to **System** > **General Settings** > **Analytics**

![screenshot-4](https://user-images.githubusercontent.com/7852494/35164441-5c3d51fc-fd18-11e7-8da4-47ac45d32d04.jpg)

Were you changing the code?

IMPORTANT: PageStudioCMS is NOT canvasCMS, a lot has changed.
