### ISSUE TITLE
Upload Video - Noting Uploaded

### ISSUE THREAD

**Issue by mdestafadilah** [pagestudiocms/cms#74]
I tested upload video, 9mb -> 200mb size, show me error, my php config allow to upload any size.. so i try in different way.

#1. I uploaded file from file_manager, it's show some limit execed .. so, i change the config.php in file_manager to ... from 1 mb to 1024 mb (1GB) ... nothing success.

![upload-video-again](https://user-images.githubusercontent.com/5575882/31267658-1d30bbd8-aaa3-11e7-8818-c678aa88400b.png)

#2. I uploaded from 'file' attachment .. with field i created. (from Content Types add). show me limit execed.. i don't know what problem here... here some image the error.

![error-upload-video](https://user-images.githubusercontent.com/5575882/31267664-22466384-aaa3-11e7-84de-46a77263578d.png)

i just figure out what going on with video uploaded .. hems... nice to know the problem or i missing config.

Thanks

**Comment by cosmomathieu** [comment]
I'll look into this on Monday and get back with you. But in the mean time can you tell me what your `php.ini` max file size upload is?  What are the values to the following keys in `php.ini`?
```
memory_limit = 32M
upload_max_filesize = 24M
post_max_size = 32M
```

**Comment by mdestafadilah** [comment]
Yes it's working now, I just chmod 775 my cms assets .. and it's work with 1024M.
