### ISSUE TITLE
HTTPS not work..

### ISSUE THREAD

**Issue by mdestafadilah** [pagestudiocms/cms#75]
Do you have configured for https access? 

i have url with: http://rsuppersahabatan.co.id/ but can't https redirectly?

if i have folder, ex: https://www.rsuppersahabatan.co.id/roundcube (webmail)

do you have suggestion?

**Comment by cosmomathieu** [comment]
Try adding `/roundcube` like so `$config['ssl_pages'] = ['roundcube'];`. I don't remember exactly, but I have used ssl before.
Do you want to use HTTPS across the entire site or just one page?

**Comment by mdestafadilah** [comment]
Yes, I need HTTPS entire the domain, not sub domain, i test some folder inside webroot, it's show HTTPS, but if website, only HTTP... I try with .htaccess from a get on stackoverflow ... nothing work, it's your cms config? or it's about hosting problem...

**Comment by mdestafadilah** [comment]
Yes, it's working now, but some CSS file has cached before, any suggestion?

**Comment by cosmomathieu** [comment]
Not sure what you mean here "CSS file has cached before". Can you show me an screenshot?

**Comment by mdestafadilah** [comment]
I will close this issue, about HTTPS ... and fixed with add `$config['ssl_pages'] = ['/','cms'];`. Thanks ... yes, before we use let's encrypt ... cache delivered with HTTP ... but now delivered with HTTPS. 
![cache](https://user-images.githubusercontent.com/5575882/36881532-2ddbf9c6-1e01-11e8-91e3-5feb89e9c95e.png)

Thanks for reply!

**Comment by cosmomathieu** [comment]
Great! I'm glad it's working for you. When I have some time I will upgrade the software.
