### ISSUE TITLE
Support API Service

### ISSUE THREAD

**Issue by mdestafadilah** [pagestudiocms/cms#77]
Hi, Have you add Guzzle as default API Client/ Server ? 

I'm using Http php Plugin for API Client.. it's working on production ... but in development, sometimes it's too long for responses.

**Comment by cosmomathieu** [comment]
No, I have not added Guzzle. I did not have plans to add it either. Do you want to create a pull request?

**Comment by mdestafadilah** [comment]
yes i do, but i'm not promise, Guzzle is too fast for updated .. have you create documentation how to create modules in pagestudiocms? or i'm missing read..

**Comment by cosmomathieu** [comment]
No I have not created documentation on how to create modules. I'll create one soon.

**Comment by cosmomathieu** [comment]
@mdestafadilah here is rough-draft of the documentation on how to create modules https://gist.github.com/cosmomathieu/663edda84fa671e58a3be3ef7da808b4

Feel free to add questions there. I'm closing this issue for now.
