### ISSUE TITLE
KCFinder

### ISSUE THREAD

**Issue by mdestafadilah** [pagestudiocms/cms#80]
Hi, I faced this error ... i don't know why its hapen...

kcfinder attention unknown error 

![Screenshot_2019-05-13_11-26-14](https://user-images.githubusercontent.com/5575882/57595898-f4c7cd80-7571-11e9-85ef-e634edd37f97.png)

any idea?

**Comment by cosmomathieu** [comment]
No. How do I generate this error?

**Comment by mdestafadilah** [comment]
I think the problem in my server production ... access privilages, i test in windows it's work, i will close this issue. Thanks for your fast reply brother.
